### ISSUE TITLE
Getting "cannot read property cookie of null" while running unit test cases with js-dom (jest package)

### ISSUE THREAD

**Issue by chaitanya71998** [js-cookie/js-cookie#759] opened 2022-01-27 15:55 UTC
* While running all the unit test cases, getting `Type cannot read property cookie of null`
* not knowing from where to debug, even the error is coming in different tests where the  js-cookie is not used.
* but mocked cookies in different files as required
   mock implementaion
```
import Cookies from 'js-cookie'
   Cookies.get = jest.fn().mockImplementation(() => 'random_cookie')
```

* pardon for not having a reproducible step, the issue is coming only when I run all the test cases
versions used:
-> "@testing-library/jest-dom": "4.2.4",
-> "js-cookie": "2.2.1",
->  "react-scripts": "4.0.3",
-> "react": "^16.12.0"

![image](https://user-images.githubusercontent.com/46353549/151392219-d7d45183-c98b-4dde-80bf-aba47a74c975.png)

**Comment by carhartl** [comment] 2022-01-27 19:38
Hard to figure out given the lack of information. It looks as if `document` is `null` in the environment you are running the tests in. Are you sure you are not accidentally running tests in a node environment?

The other thing I vaguely remember is that when doing some sort of SSR such a problem can occur. But in general it looks like you’re running the library in an environment it’s not supposed to run in.

Closing, not a bug.

**Closed by carhartl** 2022-01-27 19:38 UTC
Labels: bug

**Comment by carhartl** [comment] 2022-01-27 19:53
This might have a hint: https://stackoverflow.com/questions/57113871/jsdom-document-is-not-defined

Look for how the jsdom environment is created..

**Comment by chaitanya71998** [comment] 2022-01-29 03:39
> This might have a hint: https://stackoverflow.com/questions/57113871/jsdom-document-is-not-defined
> 
> Look for how the jsdom environment is created..
thanks @carhartl  even this didn't help out

**Comment by chaitanya71998** [comment] 2022-03-07 03:33
mocking js-cookie package cleared the issue, but yet dont know why this type error appeared
