### ISSUE TITLE
can't recognition "/" !

### ISSUE THREAD

**Issue by hezedu** [js-cookie/js-cookie#101] opened 2015-10-09 15:27 UTC
the cookie is `"/test":"hello world"`(not %2Ftest )
use Cookies.remove("/test"); is fail

**Comment by hezedu** [comment] 2015-10-10 14:56
the RFC 6265 .
you are right.

**Comment by FagnerMartinsBrack** [comment] 2015-10-10 15:37
Probably server-side issue related to #70

**Comment by hezedu** [comment] 2015-10-11 12:30
is so bad.  now, I think you are wrong

**Comment by hezedu** [comment] 2015-10-11 12:48
the remove at nodejs is not working.
```js
//server set cookie
this.cookie('test', 'obbbbbbbbb');

//client
  console.log("test is "+Cookies.get('test'));
  Cookies.remove('test');
  console.log("test is "+Cookies.get('test'));

/*
result:
test is obbbbbbbbb jquery-jade_out.js:371
test is undefined 
*/
```
but 
![cookie2](https://cloud.githubusercontent.com/assets/8508437/10416832/5dd2a1be-7059-11e5-86b3-aea621b47285.png)
and reload:
![cookie](https://cloud.githubusercontent.com/assets/8508437/10416829/34c2862c-7059-11e5-9e0f-2546d899a942.png)

**Comment by FagnerMartinsBrack** [comment] 2015-10-12 01:32
You need to pass the same attributes you used to set in the server. If you set in the server without any attributes, then you need to use `Cookies.remove( "test", { path: "" });` because js-cookie by default uses `Path: /` as [specified in the docs](https://github.com/js-cookie/js-cookie/tree/5afa5d967d8f6b5d2a498926ae3e98e9a1c4857d#path).

**Comment by hezedu** [comment] 2015-10-12 02:53
The cookie's key : 
https://github.com/expressjs/cookie-parser/issues/20#issuecomment-147212746

**Comment by hezedu** [comment] 2015-10-12 03:09
Server Defaults path is “/” too.
This is an asynchronous problem：
```js
  $(window).load(function(){
    Cookies.remove('test');
    console.log(document.cookie);
  });
//It's OK!
```
Is I am so bad!  haha.

**Comment by FagnerMartinsBrack** [comment] 2015-10-12 03:13
As from [my comment in the issue you linked](https://github.com/expressjs/cookie-parser/issues/20#issuecomment-147280663), the slash (`/`) is not allowed in the cookie's name, therefore it is encoded accordingly by js-cookie upon write.

* If the server is able to send `/` without encoding it, then js-cookie will just ignore.
* If you want to decode correctly in the server you can probably do something like:

```javascript
value.replace( /(%[0-9A-Z]{2})+/g, decodeURIComponent );
```

> This is an asynchronous problem

I don't understand, there is no asynchronous operation within js-cookie.

**Comment by hezedu** [comment] 2015-10-12 03:29
I don't say the asynchronous  problem is you
I think It's maye because the `Connection:keep-alive`

**Comment by hezedu** [comment] 2015-10-12 11:20
the ajax's cookie remove:
```js
setTimeout(function(){
 Cookies.remove('test');
});
```

**Comment by FagnerMartinsBrack** [comment] 2015-10-12 17:48
If the problem is not related to js-cookie, then I would suggest to try other channels, like creating a question in [StackOverflow](http://stackoverflow.com).

Closing for now. To keep going on this I need some code that shows a problem in js-cookie clearly, otherwise there's nothing I can do.

**Closed by FagnerMartinsBrack** 2015-10-12 17:48 UTC
