### ISSUE TITLE
Cookie for subdomain

### ISSUE THREAD

**Issue by jadeye** [js-cookie/js-cookie#81] opened 2015-08-27 13:49 UTC
[carhartl](https://github.com/carhartl)-PLEASE DO NOT CLOSE THIS IN THE NEXT 20 SECONDS!!!
Thank you [FagnerMartinsBrack](https://github.com/FagnerMartinsBrack) FOR YOU [PREVIOUS ANSWER](https://github.com/js-cookie/js-cookie/issues/80)!!!
I have tried replacing `path:''` with `domain` but in vain.
I have tried combining the two but still without luck :-(

I would appreciate it if you could take a look...
[site](http://oc2000.polumetis.net/)

Now if you change the languages from the top menu,
This script is to change that cookie:

`Cookies.remove('googtrans',{path:'',domain: 'oc2000.polumetis.net'});
Cookies.remove('googtrans',{path:'',domain: '.oc2000.polumetis.net'});
Cookies.remove('googtrans',{path:'',domain: '.polumetis.net'});
Cookies.set('googtrans', '/en/<?php echo $lang; ?>',{path:'',domain: '.oc2000.polumetis.net'});
Cookies.set('googtrans', '/en/<?php echo $lang; ?>',{path:'',domain: 'oc2000.polumetis.net'});
Cookies.set('googtrans', '/en/<?php echo $lang; ?>',{path:'',domain: '.polumetis.net'});`

Something is not working here...
The script is creating a new cookie but still it creates the domain cookie as well....
& it is not removing them at all...
Why?
Thank you again for your time

**Comment by carhartl** [comment] 2015-08-27 14:07
It may be that a value of "" is not a valid/useful value for path. From where you've written such a cookie it may not be accessible (this is possible), thus removing won't work either (technically, removing is writing a cookie with a special set of attributes). Can you try without path (or a different value) and see what happens? Also make sure to create a blank state, cookie-wise.

**Comment by FagnerMartinsBrack** [comment] 2015-08-27 16:09
> It may be that a value of "" is not a valid/useful value for path

It may be useful if you want the cookie to be [valid to the path of the current page](https://github.com/js-cookie/js-cookie/tree/v2.0.2#basic-usage) while no path will fallback to the default (valid to the whole site: `/`).

@jadeye 
Unfortunately we can't inspect a live site to look for the root cause of the problem. [We recommend]((https://github.com/js-cookie/js-cookie/blob/master/CONTRIBUTING.md#issues)) to track down a problem and provide a [simplified example](http://sscce.org) that fails in order for us to look into, as suggested in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/master/CONTRIBUTING.md#issues).

**Comment by FagnerMartinsBrack** [comment] 2015-08-27 16:15
If you use the following code it should create and remove the cookie correctly:

```javascript
Cookies.set( 'googtrans', '/en/US', { path: '', domain: 'oc2000.polumetis.net' });
Cookies.remove( 'googtrans', { path: '', domain: 'oc2000.polumetis.net' });
```

**Comment by jadeye** [comment] 2015-08-27 17:55
I understand all that's said...still it is creating a cookie for domain as well...anything I can do to check this out?

**Comment by FagnerMartinsBrack** [comment] 2015-08-27 19:02
So let me see if I get this right. What you are saying is that, after the following code executes:

```javascript
Cookies.set( 'googtrans', '/en/US', { path: '', domain: 'oc2000.polumetis.net' });
Cookies.remove( 'googtrans', { path: '', domain: 'oc2000.polumetis.net' });
```

the browser is creating 2 cookies. One with the domain, one without the domain and the `Cookies.remove` call is ignored?

**Comment by jadeye** [comment] 2015-08-27 19:19
This is the current running code:

`console.log('Init lang - <?php echo $lang; ?> - $v lang - <?php echo $v["lang"]; ?>');`
`Cookies.remove('googtrans',{ domain: 'oc2000.polumetis.net'});`
`Cookies.remove('googtrans',{ domain: '.polumetis.net'});`
`console.log('After remove - ' + Cookies.get('googtrans'));`
`Cookies.set('googtrans', '/en/<?php echo $lang; ?>',{path:'/',domain: '.oc2000.polumetis.net'});`
`Cookies.set('googtrans', '/en/<?php echo $lang; ?>',{ domain: 'oc2000.polumetis.net'});`
`Cookies.set('googtrans', '/en/<?php echo $lang; ?>',{ domain: '.polumetis.net'});`
`console.log('AFTER SET NEW - ' + Cookies.get('googtrans'));`

**Comment by jadeye** [comment] 2015-08-27 19:23
This is correct...and the code above obviously is modified...I have this code working on a different domain...and it worx great:

`				Cookies.remove('googtrans',{path:'', domain: 'jerusalempetshop.com'});`
`				Cookies.remove('googtrans',{path:'', domain: '.jerusalempetshop.com'});`
`				console.log('After remove - ' + Cookies.get('googtrans'));`
`				Cookies.set('googtrans', '/en/fr',{path:''}); `
`				console.log('AFTER SET NEW - ' + Cookies.get('googtrans'));`

I am pretty sure its got something to do with the subdomain...

**Comment by jadeye** [comment] 2015-08-27 19:31
And this worx as well on that sub-domain:

`                                Cookies.remove('googtrans',{path:'', domain: 'oc2000.polumetis.net'});`
`                                Cookies.remove('googtrans',{path:'', domain: '.oc2000.polumetis.net'});`
`                                console.log('After remove - ' + Cookies.get('googtrans'));`
`                                Cookies.set('googtrans', '/en/<?php echo $lang; ?>',{path:''});`

Don't you think this is strange behavior??

**Comment by FagnerMartinsBrack** [comment] 2015-08-27 19:55
This might be something related on creating 2 cookies with the same name, see https://github.com/js-cookie/js-cookie/issues/37#issuecomment-113964814.

I formatted one of your comments to use JS code highlight properly, in case you are wondering how to do it. Also, it would help a lot removing the PHP code from the examples.

**Comment by carhartl** [comment] 2015-08-27 22:17
The domain attribute for a cookie is expected to have a leading dot. If that does not exist, it will internally be added. If you change your code to consistently use values with a leading dot, does it change anything?

I.e. `.oc2000.polimetis.net` instead of `oc2000.polumetis.net` etc. 

In depth: http://stackoverflow.com/questions/1062963/how-do-browser-cookie-domains-work

**Comment by FagnerMartinsBrack** [comment] 2015-08-27 23:22
The domain attribute is so confusing, It would be very nice if we could find a way to test it across all browsers and document the inconsistencies to provide a better interface. js-cookie currently just delegates the behavior to `document.cookie` as if it was created using `document.cookie = "c=v; domain: example.com"`.

**Comment by carhartl** [comment] 2015-08-28 07:10
Let's try to simplify things a bit, in the originally code posted I can see redundant cookies being created and if we get this right first we can see if there's still a problem.

Of the three cookies created, only the one created with the domain "polumetis.net" (which should be changed to ".polumetis.net") is necessary. This cookie is avalailable on any subdomain of that domain, for instance "oc2000.polumetis.net". 

Once this of fixed, does a problem remain?

Cookies with the same name and slightly different attributes may shadow each other in unforeseeable ways.

**Comment by jadeye** [comment] 2015-08-28 10:40
I will test all this later on today and post the results

**Comment by carhartl** [comment] 2015-08-28 10:45
@FagnerMartinsBrack 

> It may be useful if you want the cookie to be valid to the path of the current page while no path will fallback to the default (valid to the whole site: /).

Ah right, I still can't make my mind remember counter-intuitive values.

**Comment by FagnerMartinsBrack** [comment] 2015-09-13 20:21
I created an issue to enhance the domain docs to account for some additional details regarding on how the sub-domain syntax works: #87.

I will be closing this for now since this is just a browser-related behavior, the best we can do is document it to make it clearer.

**Closed by FagnerMartinsBrack** 2015-09-13 20:21 UTC

**Comment by FagnerMartinsBrack** [comment] 2015-09-19 04:57
> Cookies with the same name and slightly different attributes may shadow each other in unforeseeable ways.

Ref. https://github.com/js-cookie/js-cookie/issues/37#issuecomment-113964814

**Comment by FagnerMartinsBrack** [comment] 2015-09-19 13:28
Created #91.
