### ISSUE TITLE
get('name', { path: '' }) creates a cookie!

### ISSUE THREAD

**Issue by sb10** [js-cookie/js-cookie#145] opened 2016-02-25 14:22 UTC
I'm using js-cookie for the first time (v2.1.0). I initially used the get command incorrectly by trying to pass it the path. This unexpectedly creates a cookie!

Using chrome, looking at my Resources->Cookies->localhost, I first confirm I have no cookie named 'columns'.

Then I refresh this page:

`<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Cookie Test</title>
        
        
        <script src="/js/js.cookie-2.1.0.js"></script>
    </head>
    <body>
        <p>Hello</div>
        
        <script type="text/javascript">
            var userCols = Cookies.get('columns', { path: '' });
            if (userCols) {
                console.log('got cols: ' + userCols);
            }
        </script>
    </body>
</html>
`

The javascript console says:
got cols: columns={%22path%22:%22%22}; path=/

And I can see that weird new cookie.

I don't know if this is undocumented intended behaviour of get(), or if it's a bug. Either way, it's quite surprising for get() to ever create a cookie.

**Comment by FagnerMartinsBrack** [comment] 2016-02-26 01:14
> I initially used the get command incorrectly by trying to pass it the path. This unexpectedly creates a cookie!

If the API is used incorrectly, then the behavior is unexpected.

> I don't know if this is undocumented intended behaviour of get(), or if it's a bug. Either way, it's quite surprising for get() to ever create a cookie.

It is not a documented behavior because it is not a feature. It is neither a bug because it is not documented. It is just a side effect of using the API incorrectly. If we define the behavior and document it, then we need to support forever and never change it until the next major version release.

**Comment by FagnerMartinsBrack** [comment] 2016-02-26 01:26
Just to explain what is going on here:

Internally we treat `get` and `set` with the same api `fn(name, value, attributes)`. The difference is that there is a conditional where, if you pass more than 1 arguments to the api it treats as a setter, otherwise it treats as a getter.

In this case when you use `Cookies.set(name, attributes)` you are triggering the code path that uses the `fn(name, value)` and therefore the object is tread as a value that should be stringified to JSON (`fn('columns', { path: '' })`)

**Could you have created a better default?**

Maybe. The thing is that by creating a single function you are able to trade the cyclomatic complexity and ambiguous reference for less bytes in the code. That is why we are able to achieve ~800 bytes gzipped despite the many features the lib has.

Since one should never pass arguments that are not documented in the public API, I see no reason for changing this because there is not really anything to fix.

**Comment by FagnerMartinsBrack** [comment] 2016-03-04 11:50
I will close this as wrong usage, it doesn't seems to make sense deciding and supporting a behavior for something that is not documented.

**Comment by mcd-php** [comment] 2016-04-05 07:55
+1

Please document severe caution for this unexpected behavior - get() should not put anything !

This robbed me of some paid worktime, wireshark captures and swearings ;(

**Comment by FagnerMartinsBrack** [comment] 2016-04-05 11:01
@mcd-php Why would we document something that doesn't exist? If you are using the API incorrectly it is at your own risk! js-cookie promises to work as it is documented, and it does.

However you are the second person to use this incorrectly, therefore I am convinced that at least we shouldn't leave the default side-effect of creating a cookie when you pass the second argument as an Object Literal. We will consider that this wrong usage is common enough for whatever reason to justify at least a verification to ensure this doesn't happen.

We can promise that, but we can't promise that the `.get(String, Object)` API exists or that anyone is free to use it because **it is not documented, and never was**.

**Comment by FagnerMartinsBrack** [comment] 2016-04-05 12:14
PR #168.

**Closed** 2016-04-09 14:51 UTC
