### ISSUE TITLE
Cookies.get() always returns empty when used with jsdom.

### ISSUE THREAD

**Issue by lynndylanhurley** [js-cookie/js-cookie#236] opened 2016-07-14 19:11 UTC
In this block of code:

```js
if (this.json) {
  try {
    cookie = JSON.parse(cookie);
  } catch (e) {}
}
```

If `this` is undefined, it will throw an error causing a `Cookies.get()` to always return an empty `{}`.

The solution is to change the conditional to the following:

```js
if (this && this.json) {
  try {
    cookie = JSON.parse(cookie);
  } catch (e) {}
}
```

This is only failing in my test suite where jsdom is used instead of a browser. Everything seems to work in the browser.

Working on a PR.

**Comment by FagnerMartinsBrack** [comment] 2016-07-14 23:58
Hey, thanks for the PR and issue. For the purpose of documenting the use case, can you please post a simplified example using jsdom where this causes a problem?

**Comment by FagnerMartinsBrack** [comment] 2016-07-15 12:48
I will assume the OP is not interested in working in this issue anymore given I had no answer [to this comment](https://github.com/js-cookie/js-cookie/pull/237#issuecomment-232863880) and [an alternative solution was found](https://github.com/lynndylanhurley/redux-auth/commit/03abc7bf583ee5ceaed147efab6b023060e38c6d). Still, this is a use case that I am interested in investigating to see if it is worth supporting. Let's keep it open then.

**Comment by thasmo** [comment] 2016-07-20 11:45
@FagnerMartinsBrack I don't use `jsdom` but in my case `Cookies.get()` and `Cookies.get('name')` always returns an empty object. Setting cookies works, reading not at all. This happens for me in latest Firefox, Chrome and in IE 11; probably in all other browsers too. The fix from @lynndylanhurley works.

**Comment by thasmo** [comment] 2016-07-20 11:59
@FagnerMartinsBrack, this only happens if [cash.js](https://github.com/kenwheeler/cash) is included **before** `cookie-js`. If I include `cookie-js` as first script, it works fine.

**Comment by FagnerMartinsBrack** [comment] 2016-07-20 14:21
@thasmo Can you please provide a [SSCCE](http://sscce.org) and create a new issue about this case?

**Comment by FagnerMartinsBrack** [comment] 2016-07-31 08:11
Pinging @thasmo again

**Comment by FagnerMartinsBrack** [comment] 2016-08-22 13:46
After reviewing all this again I still fail to understand why `this` is undefined when running the `this.json` line and why we need Babel, Mocha and a lot of other dependencies to reproduce the issue in a test (see [this discussion](https://github.com/js-cookie/js-cookie/pull/237/files#r70922399)).

I still don't understand very well how jsdom is being used here. The only other cookie API I know that supports jsdom is [this one](https://github.com/ScottHamper/Cookies/tree/84f0b4ed2a22cddc5c54347ff7066775299dab43#use-in-commonjsnode-environments-without-window), and in that case, it exposes a factory method that accepts a `window` instance that can be produced by jsdom. This report seems to be [using it differently with jsdomify](https://github.com/lynndylanhurley/js-cookie/blob/915e55c3c6ac143675f9d6e28c3fffb4ba9143ac/test/es6-import.js#L8):

```javascript
  const key = 'test-key';
  const val = 'test-val';
  jsdomify.create();
  Cookies.set(key, val);
  const result = Cookies.get(key);
  assert.equal(val, result);
```

I will try to use `jsdomify.create();` with js-cookie in the current node test suite we have and see if I can reproduce the problem with a failing test.

**Comment by FagnerMartinsBrack** [comment] 2016-08-22 14:11
According to [this comment](https://github.com/js-cookie/js-cookie/pull/237#issuecomment-232858028):

> So when we try to say this.json, it throws an error because this is undefined in this context.

From what I understand from the test above in the related PR, if using `jsdomify.create();` it should somehow mess with `this` and make it undefined when executing `Cookies.set(key, val);` and `Cookies.get(key);` afterwards.

That said, I imported [the version 2.1.0 of jsdomify](https://github.com/dmatteo/jsdomify/tree/v2.1.0) as a devDependency running on node 5 and [the current js-cookie code on master](https://github.com/js-cookie/js-cookie/blob/72d05c27ebfb99aa8b6ae8f1b46210e223e815b9/src/js.cookie.js) locally and tried to reproduce the issue with this test:

```javascript
/*jshint node:true */
exports.node = {
	should_not_throw_error_when_using_jsdomify: function (test) {
		test.expect(0);
		var Cookies = require('../src/js.cookie');
		var jsdomify = require('jsdomify');
		jsdomify.create();
		Cookies.set('c', 'v');
		Cookies.get('c');
		test.done();
	}
};
```

The expected was a failing test in js-cookie, but the failure was in jsdomify. `jsdomify.create()` doesn't exist and it exposes instead a `jsdomify.default.create()`. I tried to use that and expected a failure:

```javascript
/*jshint node:true */
exports.node = {
	should_not_throw_error_when_using_jsdomify: function (test) {
		test.expect(0);
		var Cookies = require('../src/js.cookie');
		var jsdomify = require('jsdomify');
		jsdomify.default.create();
		Cookies.set('c', 'v');
		Cookies.get('c');
		test.done();
	}
};
```

Instead of a failure, I got a success, which means that I couldn't reproduce the problem.

Besides, there's no documentation of `jsdomify.default` in the `jsdomify` documentation (ping @dmatteo). Even if the test failed, we would not test for the side effects of an undocumented API.

Without understanding the problem, it is impossible to find an optimal solution. I will be closing this until someone is keen to [provide a SSCCE](http://sscce.org/) or explain objectively why we need tons of dependencies to reproduce the problem.

**Comment by dmatteo** [comment] 2016-09-02 04:08
Hey @FagnerMartinsBrack, I finally managed to get around this thread and try and reproduce whatever issue was here, without success though, or actually without failures...

I've created a small repo here https://github.com/dmatteo/jsCookieRepro that will also help clear out the `jsdomify.default` case. Good point on the fact that the CommonJS use case is not documented on the README, I will add that asap.

There are 3 branches on the repo:
* **master**: running on `jsdomify 3.0.0` which depends on `jsdom 9.4.2`
  * It's using ES6 syntax, including ES6 modules: `import jsdomify from 'jsdomify'`
  * Tests can be run with `./node_modules/.bin/mocha --compilers js:babel-register`

* **no-transpiling**: running on `jsdomify 3.0.0` which depends on `jsdom 9.4.2`
  * Dear 'ol ES5, which means `var jsdomify  = require('jsdomify').default`
  * The `.default` part is not a `jsdomify` specific thing, but it's there because the library is exported as a default ES6 module and then transpiled via babel before publishing, so it can be used also via CommonJS
  * Tests can be run with `./node_modules/.bin/mocha`

* **jsdomify-2**: running on `jsdomify 2.1.0` which depends on `jsdom 8.2.0`
  * Again ES6 here, but using the version of `jsdomify` that was mentioned in the issue here.
  * Tests can be run with `./node_modules/.bin/mocha --compilers js:babel-register`

--- 

All the (2) tests in the 3 branches passes, so I'm not sure what was the issue here.

Does that help in any way?

**Comment by FagnerMartinsBrack** [comment] 2016-09-02 04:27
> Does that help in any way?

I will take a look for 2.1.4

**Comment by FagnerMartinsBrack** [comment] 2016-09-17 03:30
@dmatteo I find it very hard to run the project because there's no documentation of how to run it. I have never built something using babel before and I don't have a lot of time to look at it.

@lynndylanhurley, according to @dmatteo:

> I finally managed to get around this thread and try and reproduce whatever issue was here, without success though, or actually without failures...

It seems that we are still unable to reproduce whatever issue was going on here. In order to continue on this issue, we need a [SSCCE](http://sscce.org) that proves this problem is with js-cookie and not with the unrelated dependencies (babel, jsdom, jsdomify, etc.).

It will be much appreciated if anyone reading this could help out to identify what is going on, if somebody does it then we can reopen this.

Thanks for everyone involved.

**Closed by FagnerMartinsBrack** 2016-09-17 03:30 UTC

**Comment by montogeek** [comment] 2016-10-28 19:17
What this fixed?

**Comment by FagnerMartinsBrack** [comment] 2016-10-28 23:13
@montogeek It is not clear, feel free to do a `git bisect` in your machine and come with what this fixed if you can.
