### ISSUE TITLE
how to set a cookie for localhost in chrome ?

### ISSUE THREAD

**Issue by OneNewLife** [js-cookie/js-cookie#247] opened 2016-07-29 02:57 UTC
According to the [chromium project](https://bugs.chromium.org/p/chromium/issues/detail?id=56211), we cannot set cookies for localhost anymore.

so how can we hack that? Is there any hacking way to set a cookie for localhost?

**Comment by FagnerMartinsBrack** [comment] 2016-07-29 05:25
Duplicated of https://github.com/js-cookie/js-cookie/issues/129#issuecomment-179700594. Please use search next time.

**Comment by FagnerMartinsBrack** [comment] 2016-07-29 05:26
Do you have a link to the relevant chromium statement? I thought it was a duplicate of [this one](https://github.com/js-cookie/js-cookie/issues/129#issuecomment-179700594), but doesn't seems so.

**Comment by OneNewLife** [comment] 2016-07-29 06:07
https://bugs.chromium.org/p/chromium/issues/detail?id=56211 @FagnerMartinsBrack

**Comment by FagnerMartinsBrack** [comment] 2016-07-29 06:08
Can you please paste the relevant comment from that thread so that we can understand what is going on?

**Comment by OneNewLife** [comment] 2016-07-29 06:43
uh, the problem is **we cannot set cookies for localhost, can anyone hack this**.

exactly, this issue is not about `document.cookie` API. but u should know,when u call `document.cookie` API in chrome, it actually call the ChromeDriver, and finally date back to the this issue.

if u wanna know more about this, u can check the chromium project.I have found sth in `chromium/chrome/browser/net/cookie_policy_browsertest.cc`(from line 63 to 81):

```
  // Change the host name from 127.0.0.1 to www.example.com so it triggers
  // third-party cookie blocking if the first party for cookies URL is not
  // changed when we follow a redirect.
  ASSERT_EQ("127.0.0.1", redirected_url.host());
  GURL::Replacements replacements;
  replacements.SetHostStr("www.example.com");
  redirected_url = redirected_url.ReplaceComponents(replacements);

  std::string cookie =
      content::GetCookies(browser()->profile(), redirected_url);
  ASSERT_EQ("", cookie);

  host_resolver()->AddRule("www.example.com", "127.0.0.1");

  ui_test_utils::NavigateToURL(browser(),
                               GURL(url.spec() + redirected_url.spec()));

  cookie = content::GetCookies(browser()->profile(), redirected_url);
  EXPECT_EQ("cookie2", cookie);
```

**Comment by FagnerMartinsBrack** [comment] 2016-07-29 06:50
> we cannot set cookies for localhost, can anyone hack this

Is that in the link you posted?  I tried to search the String in the thread and got no result.

> exactly, this issue is not about document.cookie API. but u should know,when u call document.cookie API in chrome, it actually call the ChromeDriver, and finally date back to the this issue.

To be honest, I don't know and don't have time to understand how Chrome internals work since it is irrelevant for the purpose of js-cookie. That's why I asked for a high-level overview of what is going on.

In summary, is the browser now blocking cookies despite the `--enable-file-cookies` flag?

If that's the case, then the only thing we can do now is document the behavior and recommend using a lightweight static server instead, because it is out of scope of this project to provide hacks for something that the Chrome team deliberately choose to disallow.

**Comment by FagnerMartinsBrack** [comment] 2016-07-31 07:12
Closing due to the lack of feedback from [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). Feel free to comment here to open up the discussion again

**Closed by FagnerMartinsBrack** 2016-07-31 07:12 UTC

**Comment by roson** [comment] 2019-12-20 06:57
I've got the same problem how cookies are  managed by browser for localhost domain for http protocol.


For example. I run an application on development environment.

- Use domain 'localhost'

`Request URL: http://localhost:8080/app/login.xhtml`

`Response Header`
`Set-Cookie: JSESSIONID=5F1F72C746AC8F7972D475C85B7AFC72; Version=1; Comment="Keeps you logged in."; Path=/app/; HttpOnly`

Enter login and password
`Request URL: http://localhost:8080/app/login.xhtml;jsessionid=6AEA612145F941A0F56A23B50EB48BD2`

Session id is send in URL. I can not log in.
Server does not accept URL rewriting (tracking mode: cookie).

- Use ip '127.0.0.1'

`Request URL: http://127.0.0.1:8080/app/login.xhtml`

`Response Header`
`Set-Cookie: JSESSIONID=43C0A84771959B80901A18EE95CA030F; Version=1; Comment="Keeps you logged in."; Path=/app/; HttpOnly`

Enter login and password
`Request URL: http://127.0.0.1:8080/app/login.xhtml`
`Request Header`
`Cookie: JSESSIONID=43C0A84771959B80901A18EE95CA030F`

Now session id is send in headers. I can log in.


So when I use ip '127.0.0.1' session id is send in header, 
but when I use domain 'localhost' session id is send in URL.
It happen for HTTP protocol. For HTTPS protocol it works.

Is bug or secure issue?

**Comment by carhartl** [comment] 2019-12-20 08:03
https://github.com/js-cookie/js-cookie/issues/486#issuecomment-453910762

**Comment by FagnerMartinsBrack** [comment] 2019-12-20 08:04
@roson I don't see an example using js-cookie code, from the examples you posted it seems you're only using server-side.

**Comment by roson** [comment] 2019-12-21 00:33
Yes. In the example it is used server-side.

I've checked my browser settings about blocking saving and reading cookie data
Settings | Site settings | Cookies and site data
I've got 'localhost' in Block list.
Set-Cookie was not stored due to this setting.

So I removed 'localhost' from Block list and now it works.
