### ISSUE TITLE
Using js-cookie on third party sites / noConflict

### ISSUE THREAD

**Issue by unuseless** [js-cookie/js-cookie#646] opened 2020-07-13 16:05 UTC
The bug happens in the following circumstance:

A site uses requirejs for loading js (called parent site).  In this parent site third party javascript snippets are used.  The third party scripts (i.e. js based polls, popups, counters, ...) have no access to the requirejs loading environment of the parent site.

js-cookie is used in such a third party script.  Because the third party script does not know in which environment js-cookie is loaded, they should use the `noConflict` method.  That works well if the parent site does not use requirejs.  However if the parent site uses requirejs, the `noConflict` method throws an error because it is not exported.

This issue is very similar to #234 .

**Expected behavior**
js-cookie allows `noConflict` under all circumstances, even if the host site uses requirejs.

**Comment by carhartl** [comment] 2020-07-15 05:46
@unuseless You have an idea how to solve this?

**Comment by unuseless** [comment] 2020-07-15 11:46
@carhartl What I've done to circumvent the problem is: editing the code of js-cookie like this:
```
/*!
 * JavaScript Cookie v2.2.1
 * https://github.com/js-cookie/js-cookie
 *
 * Copyright 2006, 2015 Klaus Hartl & Fagner Brack
 * Released under the MIT license
 */
;(function (factory) {

    // 2020.07.13 edited to remove check for module loader, as in
    // third party script must be able to load through
    // global object


    // var registeredInModuleLoader;
    //     if (typeof define === 'function' && define.amd) {
    //     	define(factory);
    //     	registeredInModuleLoader = true;
    //     }
    //     if (typeof exports === 'object') {
    //     	module.exports = factory();
    //     	registeredInModuleLoader = true;
    //     }
    //     if (!registeredInModuleLoader) {
    var OldCookies = window.Cookies;
    var api = window.Cookies = factory();
    api.noConflict = function () {
	window.Cookies = OldCookies;
	return api;
    };
    //	}
}(function () {
....
```
i.e. commenting out the check for the module loader which disables the `noConflict`. That even makes the code smaller :-)

**Comment by carhartl** [comment] 2020-07-15 12:18
🤔

We‘re currently having rollup generate this piece of code for us during build.

**Comment by carhartl** [comment] 2020-07-15 12:20
Also, it removes support for loading js-cookie as a UMD/AMD Module, so that‘s clearly not an option for us.

**Comment by unuseless** [comment] 2020-07-15 20:06
An alternative is:
```
 //     if (!registeredInModuleLoader) {
    var OldCookies = window.Cookies;
    var api = window.Cookies = factory();
    api.noConflict = function () {
	window.Cookies = OldCookies;
	return api;
    };
    //	}
```
i.e. just remove the check for `!registeredInModuleLoader` and allow `noConflict` unconditionally.

**Comment by carhartl** [comment] 2020-07-17 06:33
The code in question (module + no conflict setup) is being generated by rollup when creating the dist, so you might want to file a ticket there.

https://github.com/rollup/rollup

**Comment by unuseless** [comment] 2020-07-17 21:41
Short question: are you using http://rollupjs.org/guide/en/#outputnoconflict ?

**Comment by carhartl** [comment] 2020-07-18 03:46
Yes: https://github.com/js-cookie/js-cookie/blob/3cc23031e6a7df1f7ef958194bf3c59742041c23/rollup.config.js#L46

**Comment by unuseless** [comment] 2020-07-20 18:06
Thanks.  I'll check into rollup, in order to understand this.

**Comment by unuseless** [comment] 2020-07-20 18:29
@carhartl I think the problem can be solved by adding the IIFE output format to rollup: https://rollupjs.org/guide/en/#outputformat .
Probably that would mean rollup would generate an extra js file for the iife format, such that js-cookie can be used both with umd and in a `<script>` tag.

**Comment by carhartl** [comment] 2020-07-20 18:49
We have: 

https://github.com/js-cookie/js-cookie/blob/3cc23031e6a7df1f7ef958194bf3c59742041c23/rollup.config.js#L25

> umd – Universal Module Definition, works as amd, cjs and iife all in one

**Comment by carhartl** [comment] 2020-07-20 19:01
I don’t think Rollup will be able to fix this, nor do we. The umd/amd detection can‘t be done conditionally. 

What you could try is to load the 3rd party scripts before any other of the parent site scripts are being loaded, if possible.

**Comment by carhartl** [comment] 2020-07-20 19:03
..or the 3rd party scripts need to build their own “iife” only builds of js-cookie. After all, we’re started providing this possibility with making use of ES modules for sources and a rollup setup.

**Comment by carhartl** [comment] 2020-07-20 19:08
Unfortunately Rollup + ES module setup came with version 3 which isn’t ready yet...

**Comment by unuseless** [comment] 2020-07-20 19:12
@carhartl Thank you for these tips.  I think you are right, a separate build is needed.

Are you open to adding to the README, in the heading "Namespace conflicts" for version 3:

If you need to use js-cookie without using UMD modules in a page which uses UMD modules, you need to rebuild js-cookie with the `rollup.config.js` output format set to `iife` instead of `umd`.  This usage might be necessary when you use js-cooke in a third party javascript application.

**Comment by mksm** [comment] 2020-08-03 21:01
I've hit the same issue as @unuseless. It would be helpful to have a solution documented for this in the interim.

**Comment by carhartl** [comment] 2020-09-08 10:33
Would it help if we distribute the package with a pre-build iife variant? Starting with v3 we should be able to adapt the rollup config to account for this, and we do already have separate umd and esm variants as part of the package.

**Comment by carhartl** [comment] 2020-09-09 06:56
Ah.. rereading earlier comment:

>Probably that would mean rollup would generate an extra js file for the iife format, such that js-cookie can be used both with umd and in a <script> tag.

This implied:

>distribute the package with a pre-build iife variant

is that correct, @unuseless?

**Comment by unuseless** [comment] 2020-09-09 08:52
@carhartl Yes, adding a variant to the package with a pre-build iife vartiant would solve the problem.  Thank you for coming back to this issue.

**Comment by carhartl** [comment] 2020-09-09 16:14
Also, I believe the umd variant shouldn’t come with noConflict, i.e. there is no need any longer.

**Comment by carhartl** [comment] 2020-09-21 12:37
I‘m starting to think, by now, v3 should allow us to drop the umd variant altogether. The package‘s `browser` field will point to a `iife` variant, modern package manager’s are able to make use of the ES module as already introduced in v3.

**Comment by carhartl** [comment] 2020-11-19 04:22
@unuseless Looking into this again, I got doubts. With an additional iife variant generated by rollup, there‘s not going to be a `noConflict()` function at all. So what‘s a 3rd party script supposed to do?

**Comment by carhartl** [comment] 2020-11-19 05:44
If 3rd party were bundling as iife, making use of he already existing iife support of the current dist, it wouldn’t pollute the global namespace in the first place with `noConflict()` not even being required.

(In a way, `noConflict()` is promoting bad practice?)

**Comment by unuseless** [comment] 2020-11-20 19:59
As I understand it, `noConflict()` makes sure it does not pollute the (global) namespace.  The issue with 3rd party scripts is that they can't control the page they are loaded in.  For example it might be possible that the page owner already loaded js-cookie.  If the 3rd party script then loads js-cookie for a second time, it must make sure that there are no conflicts.  And the 3rd party script might not be able to detect that js-cookie was loaded before itself loaded.  In my view, `noConflict()` is actually quite clean.  Even jQuery has it in order to not pollute the global namespace with `$`.

**Comment by carhartl** [comment] 2020-11-20 20:15
In the case of jQuery there was an actual need for noConflict(), as another library (Prototype) was claiming `$`.

That aside, what I mean by promoting bad practice is that 3rd party scripts shouldn’t be enabled to include a library and set it up with `noConflict()` rather than bundle itself making use of the library as a private module that would never pollute the global namespace in the first place.

**Comment by FagnerMartinsBrack** [comment] 2021-01-19 23:40
> In the case of jQuery there was an actual need for noConflict(), as another library (Prototype) was claiming $.

Besides Prototype, people where also creating a `$` global as an alias for document.getElementById(...) in their own scripts just because they didn't want to type it :D.

> rather than bundle itself making use of the library as a private module that would never pollute the global namespace in the first place.

@carhartl Not everyone uses a bundle/transpiler/compiler for various reasons (I don't) and private modules are [far from becoming mainstream](https://caniuse.com/es6-module) as they're not even supported in IE11. There's a significant number of years ahead of us until we can assume noConflict() is not required because ppl should be using Script Tag JS modules.

> @unuseless Looking into this again, I got doubts. With an additional iife variant generated by rollup, there‘s not going to be a noConflict() function at all. So what‘s a 3rd party script supposed to do with this?

If there are no side-effects I propose to remove the conditional `if (!registeredInModuleLoader) {`.

I was confused at first on why this is generated by rollup as [I wrote that exact code for js-cookie in the past](https://github.com/js-cookie/js-cookie/commit/92f8e2b04cb0ebef236e019a5900012e86a0729a), did rollup copy/pasted it for `noConflict: true`? I couldn't find the code in rollup that generates that code, can somebody help? @carhartl?

<p>
<sup>
**A meta discussion on the issues of delegating module loader code to third party build scripts**
</sup>
</p>

<p>
<sup>
Be aware some libraries are used in third-party scripts, some are not. Some libraries are also used server-side in NodeJS, some are not. It doesn't make sense to share the same `.noConflict()` code everywhere as some libraries will have different use cases for different environments, and therefore they'll host slightly different `.noConflict()` code.
</sup>
</p>

<p>
<sup>
If we delegate environment-conditional code to a third-party, we break cohesion and add more moving parts unnecessarily, increasing the cost of change for use-cases like this one.
</sup>
</p>

<p>
<sup>
There are many problems with adding more moving parts to a project unnecessarily. In the case of this issue, the act of delegating module loading code to a third party building script that we don't control cause the following issues:
</p>
</sup>

<p>
<sup>
1. Now ppl have to open an issue in js-cookie (or read one that's already been discussed), then realize that they should be reporting to Rollup **for a code change that we wrote here and could easily change here**.  That means users of js-cookie also have to inspect and understand rollup code in order to propose a change for the module loading code. This adds unnecessary cost/time on the developers using js-cookie. I for instance took a long time looking at Rollup code to identify how this `if (!registeredInModuleLoader) {` was being generated, after 20 minutes I gave up.
</sup>
</p>
<p>
<sup>
2. As new use cases like this one arise, we have to discuss publicly in an issue the proposed solution. This way we can generate a publicly searchable issue that future devs can search, read, and then potentially use it to create a report to rollup and increase the priority (assuming the problem lies with Rollup). This adds more unnecessary cost/time to the maintainers of js-cookie for the initial discussion until we conclude the problem is not with js-cookie.
</sup>
</p>

<p>
<sup>
3. It's hard to change the module loading code here in js-cookie, as we have to wait for rollup to fix in their side. It adds more cost of change (waiting time) and reduces our ability to iterate quickly ourselves within js-cookie codebase. It's like creating an app that becomes harder and harder to change over time due to the high coupling a low cohesion because we've added more moving parts where there shouldn't have been. Instead, in this specific case with js-cookie, we should make it easier and easier to change by duplicating the code here (low coupling and high cohesion).
</sup>
</p>

**Comment by realityking** [comment] 2021-07-11 15:21
I don't think I understand this issue/use-case. @unuseless do you have an example of such a third-party library using js-cookie that causes conflicts?

I don't think the 3rd party library switching to an IIFE variant would be helpful here, indeed it might be harmful. Any site that already uses js-cookie in its global (or just uses the same variables) would get their version of js-cookie overwritten with that of the 3rd party library.

IMHO the proper fix is for the 3rd-party script to adapt. They either need to ship an UMD themselves (so they'd be aware of the RequireJS environment) or use bundler to consume js-cookie and completely hide it from the environment.

**Comment by unuseless** [comment] 2021-07-11 17:00
@realityking I'm not directly involved anymore in the project which used js-cookie.  However we used js-cookie in a closure with no-conflict.  No global name space pollution happened.
We were deliberate not to use a bundler, and needed to support old browsers.
Our third party script worked basically in all environments (from IE 7 ish up to React etc.)  Often the users of a third party script are not technical, and don't even know what kind of bundler/requirejs/AMD their site uses.

Imagine you have a squarespace or wix site.  They allow you to paste a `<script>` tag somewhere, and both the script tag and the user of squarespace/wix have no idea how the site is coded.

**Comment by realityking** [comment] 2021-07-11 20:12
To be clear, when I say “ use bundler to consume js-cookie” I don’t want they should require the consumers of that library to use a bundler. Instead, one could use rollup or webpack to ship an UMD of IIFE that includes the code from js-cookie.

**Comment by unuseless** [comment] 2021-07-11 20:22
A third-party script is usually not a library.  It is a standalone script, that should work in all web pages, regardless if the hosting web page uses AMD, UMD, ...


js-cookie was nice, because it just worked, and required no node build infrastructure to use.  There's no technical reason that js-cookie would require to use a bundler.  Basically, what you propose is to require users of js-cookie to use a bundler.  The bundling problem of js-cookie is caused by rollup.  Webpack has options to bundle js-cookie standalone for old browsers.  But rollup didn't because it embraced "modern" js only (this might have changed since I looked into rollup a couple of months ago).

**Comment by carhartl** [comment] 2021-07-12 06:20
>js-cookie was nice, because it just worked, and required no node build infrastructure to use. 

and

>The bundling problem of js-cookie is caused by rollup. 

Not sure I fully understand this.. The library still just works, you can download a release and use a umd variant just so, no need for any bundler whatsoever. This hasn't changed at all. All that has changed is that we chose to use Rollup as *internal* build tooling because we wanted to start supporting ES modules. A user still doesn't have to know anything about this at all.

Thus I don't know what the bundling problem is supposed to be. What we rely on with Rollup is that it generates the noConflict code for us, but the generated code itself is exactly the same as what it was when it was glued to the source. But now, the switch to ES modules plus Rollup will allow users to build their own variant of the library (for instance iife) more easily. Before, you were forced to having to live with the noConflict code (and adapt it manually, as can be observed in this issue).

>Webpack has options to bundle js-cookie standalone for old browsers. 

When using webpack for your application and js-cookie 3 as via npm package, wouldn't this still be possible?

**Comment by carhartl** [comment] 2021-07-12 06:23
That said because this issue seems no longer relevant:

>I'm not directly involved anymore in the project which used js-cookie

and because we will allow users to build their own iife variant while maintaining upgradability (that is, no need for forking), I'd rather close this issue. At least though it won't stop us from releasing v3.

**Comment by unuseless** [comment] 2021-07-12 12:46
@carhartl Sure, go ahead and close. 
As you could see at the beginning of this thread in the code examples I gave, the bundling caused issues with js-cookie.  These issues were not present in earlier releases of js-cookie.

The issue could be resolved by adding more documentation to the README, as I proposed earlier:

> @carhartl Thank you for these tips. I think you are right, a separate build is needed.
> 
> Are you open to adding to the README, in the heading "Namespace conflicts" for version 3:
> 
> If you need to use js-cookie without using UMD modules in a page which uses UMD modules, you need to rebuild js-cookie with the `rollup.config.js` output format set to `iife` instead of `umd`. This usage might be necessary when you use js-cooke in a third party javascript application.

**Comment by carhartl** [comment] 2021-07-12 13:22
@unuseless 

I'm afraid I still don't understand:

>As you could see at the beginning of this thread in the code examples I gave, the bundling caused issues with js-cookie. These issues were not present in earlier releases of js-cookie.

The code example you gave seems to be from code from version 2 of this library (v2.2.1 to be precise), and at that point there was no bundler involved in any way. All the "noConflict" code was part of the source right away. What do you mean by "the bundling"? Your own?

See https://github.com/js-cookie/js-cookie/blob/v2.2.1/src/js.cookie.js

Fwiw, the code generated by rollup looks different (we introduced Rollup for v3):

```js
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
  typeof define === 'function' && define.amd ? define(factory) :
  (global = global || self, (function () {
    var current = global.Cookies;
    var exports = global.Cookies = factory();
    exports.noConflict = function () { global.Cookies = current; return exports; };
  }()));
}(this, (function () {
  ...
})));
```

It doesn't have the `registeredInModuleLoader` boolean flag, but still doesn't help with this issue I believe.

**Comment by 5G** [comment] 2021-07-15 13:36
Hmm, whatever changed 3 days ago seems to have broken the Stripe SCA checkout button on a lot of Wordpress sites. If possible, would recommend reverting in the meantime as it's a high severity issue.

More info & temporary fix: https://stackoverflow.com/questions/68383988/firefox-and-chrome-error-when-linking-js-cookie-uncaught-referenceerror-module

**Comment by carhartl** [comment] 2021-07-16 04:18
>The issue could be resolved by adding more documentation to the README

This topic imo is too special for the readme but we may put it to the [wiki](https://github.com/js-cookie/js-cookie/wiki)...

**Closed by carhartl** 2021-07-16 04:18 UTC
Labels: bug
