### ISSUE TITLE
IE11 not saving cookie

### ISSUE THREAD

**Issue by oninross** [js-cookie/js-cookie#175] opened 2016-04-12 09:17 UTC
Used as per documentation, it works like a charm until the user has totally "killed" the browser.  The cookie is somehow destroyed

**Comment by FagnerMartinsBrack** [comment] 2016-04-12 11:05
Have you tried using regular `document.cookie`? Can you provide a simple example where you can reproduce the problem?

**Comment by FagnerMartinsBrack** [comment] 2016-04-16 11:22
@oninross Can you at least provide some steps to reproduce the problem?

**Comment by XavierBoubert** [comment] 2016-04-19 12:58
Hello guys. I have the same problem here. I'ts seems to be a IE bug.

Some details:
- I'm using IE 11.212.10586.0

Here my console tests:
```bash
> Cookies.get('session')
"s:1a0427f0-0627-11e6-9676-7bacb97b4483.2z+JyQeWZdPfAmrs/aPzqN1OI/BGjM0SnGsQVpxUuLg"
> Cookies.set('session', 'test')
"session=test; path=/"
> Cookies.get('session')
"s:1a0427f0-0627-11e6-9676-7bacb97b4483.2z+JyQeWZdPfAmrs/aPzqN1OI/BGjM0SnGsQVpxUuLg"
> Cookies.remove('session', {path: '/'})
undefined
> Cookies.get('session')
"s:1a0427f0-0627-11e6-9676-7bacb97b4483.2z+JyQeWZdPfAmrs/aPzqN1OI/BGjM0SnGsQVpxUuLg"
> Cookies.remove('session')
undefined
> Cookies.get('session')
"s:1a0427f0-0627-11e6-9676-7bacb97b4483.2z+JyQeWZdPfAmrs/aPzqN1OI/BGjM0SnGsQVpxUuLg"
> document.cookie
"SRVGROUP=common; language=s%3Aen.ThIXEZyI%2Fvfn9QurSOUp9Bi6KNkjz%2F8VjoXJgS%2FEN58; session=s%3A1a0427f0-0627-11e6-9676-7bacb97b4483.2z%2BJyQeWZdPfAmrs%2FaPzqN1OI%2FBGjM0SnGsQVpxUuLg; SRVGROUP=common; redirect=/"
> document.cookie = document.cookie.replace(' session=s%3A1a0427f0-0627-11e6-9676-7bacb97b4483.2z%2BJyQeWZdPfAmrs%2FaPzqN1OI%2FBGjM0SnGsQVpxUuLg;', '')
"SRVGROUP=common; language=s%3Aen.ThIXEZyI%2Fvfn9QurSOUp9Bi6KNkjz%2F8VjoXJgS%2FEN58; SRVGROUP=common; redirect=/"
> document.cookie
"SRVGROUP=common; language=s%3Aen.ThIXEZyI%2Fvfn9QurSOUp9Bi6KNkjz%2F8VjoXJgS%2FEN58; session=s%3A1a0427f0-0627-11e6-9676-7bacb97b4483.2z%2BJyQeWZdPfAmrs%2FaPzqN1OI%2FBGjM0SnGsQVpxUuLg; SRVGROUP=common; redirect=/"
```

**Comment by XavierBoubert** [comment] 2016-04-19 13:01
I've found my solution by following this post:

http://answers.microsoft.com/en-us/ie/forum/ie11-iewindows8_1/ie-11-doesnt-seem-to-be-remembering/88d3d3d7-3f9e-4aa4-a272-22ea16854b0d

I have deactivate the "safe mode" in the options and now my tests works.

**Comment by FagnerMartinsBrack** [comment] 2016-04-19 13:19
> I have deactivate the "safe mode" in the options and now my tests works.

@XavierBoubert Thank you for the information, it was very useful!

Maybe we can add this into the FAQ in the Wiki once more people start reporting the same problem (I will link your research for new reports).

For now I will close this until the OP is capable of providing some example. There is nothing we can do here for this specific issue unfortunately.

**Closed by FagnerMartinsBrack** 2016-04-19 13:19 UTC

**Comment by XavierBoubert** [comment] 2016-04-19 13:29
I have found a more documented solution: http://stackoverflow.com/questions/389456/cookie-blocked-not-saved-in-iframe-in-internet-explorer

**Comment by mbraz** [comment] 2016-07-08 00:06
I have the same problem with IE11 11.0.9600.17914. @XavierBoubert not work for me.

**Comment by FagnerMartinsBrack** [comment] 2016-07-08 02:00
@mbraz Please, do not comment in close issues. If you have a problem create a new issue after [reading this](sscce.org).

**Comment by mbraz** [comment] 2016-07-08 12:11
Ok, I'll do it.

Enviado do meu iPhone 4S
