### ISSUE TITLE
js-cookie is not working incognito mode

### ISSUE THREAD

**Issue by gurmvt** [js-cookie/js-cookie#668] opened 2020-10-22 09:05 UTC
**Cookie is not setting in incognito mode.**

I am developing a Shopify app using React. I am using js-cookie to set and get cookies. The app is working fine in all browser except incognito mode. The cookie is not setting in incognito mode which crashing my app, because the app is fully dependent on cookie. I am using below code to set cookie.

`Cookies.set('storeName', storeName, { secure: true, httpOnly: false, sameSite: 'none' });`

**Please suggest me a solution to set cookie incognito mode.**

**Comment by carhartl** [comment] 2020-10-22 09:10
Please let us know which browser you‘re seeing this behavior in.

**Comment by gurmvt** [comment] 2020-10-23 04:08
> Please let us know which browser you‘re seeing this behavior in.
@carhartl I got this issue in Chrome browser.

**Comment by carhartl** [comment] 2020-10-23 06:27
I can read and write cookies in Chrome incognito mode without problems, all tests passes.. tested in Chrome 86 oh macOS 10.15.7.

<img width="1238" alt="Screenshot 2020-10-23 at 08 20 04" src="https://user-images.githubusercontent.com/21918/96963330-c9883280-1508-11eb-9d89-8f73357b2821.png">

I'm assuming there's something else going on in your application that has nothing to do with this library. For instance, in Chrome you can choose to block third-party cookies in incognito mode, maybe you're relying on such a cookie that cannot be loaded, but at this point I'm just guessing.

Closing, since issue is not reproducible. Please provide a reproducible test case should you still think it's a problem with the library.

**Comment by carhartl** [comment] 2020-10-23 06:33
Ah, wait.. it's related to the `SameSite` attribute, I can now reproduce it.

**Comment by carhartl** [comment] 2020-10-23 06:39
>Ah, wait.. it's related to the SameSite attribute, I can now reproduce it.

Nonsense, that's just me testing value "None" without secure and testing secure while on http for localhost.

**Closed by carhartl** 2020-10-23 06:39 UTC
Labels: bug
