### ISSUE TITLE
bug: error github with bower install: transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by CaptainJojo** [js-cookie/js-cookie#186] opened 2016-04-25 14:29 UTC
Since 10 minutes I have this error

```
 ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/js-cookie/js-cookie.git", exit code of #128 fatal: unable to access 'https://github.com/js-cookie/js-cookie.git/': transfer closed with outstanding read data remaining
```

I use version 2.1.0

**Fagner edit - Workarounds so far:**

> temporary fix: 
fork the repo and:
bower install https://github.com/[repo]/js-cookie.git#v[version]

-
> I managed to add this in my bower.json file:
> "js-cookie": "https://github.com/js-cookie/js-cookie/releases/download/v1.5.1/js.cookie-1.5.1.min.js"

> Then I get a index.js file containing the things, not ideal, but I don't have to fork the repo.

**Comment by CaptainJojo** [comment] 2016-04-25 14:33
It's not just bower I don't clone 

```
❯ git clone https://github.com/js-cookie/js-cookie.git
Cloning into 'js-cookie'...
fatal: unable to access 'https://github.com/js-cookie/js-cookie.git/': transfer closed with outstanding read data remaining
```

**Comment by babelfish** [comment] 2016-04-25 14:37
I'm having this problem. It's happening with the old jquery-cookie repo as well.

**Comment by msalahz** [comment] 2016-04-25 14:38
Same here

**Comment by bdaenen** [comment] 2016-04-25 14:44
+1, our builds are failing :)

**Comment by signal-intrusion** [comment] 2016-04-25 14:50
+1 Seeing this too. Going to need a fix ASAP.

**Comment by msalahz** [comment] 2016-04-25 14:50
temp solution for this is 
1- forking the repo 
2- download the zip
3- extract and rename folder to `js-cookie`
4- past the folder in your bower_components folder

**Comment by i8ramin** [comment] 2016-04-25 15:02
This is terrible. Causing Production deploy issues. Gonna have to create a hacky workaround until this is fixed. We don't commit our `bower_components` directory and it gets installed fresh on each deploy, so can't just download the zip and extract it. I guess one option is to put it in the `vendor/assets` directory for now

**Comment by panthony** [comment] 2016-04-25 15:02
Would really like a fix because unfortunately the suggested workaround is not suitable when the build is automated on different servers :cry:

**Comment by romainneutron** [comment] 2016-04-25 15:07
This seems to be related to Github guys. Just report them the issue

**Comment by akrawchyk** [comment] 2016-04-25 15:08
@panthony you can fork and change the entry in your `bower.json` to your fork's url instead of having to add the package to your project/bower_components folder.

**Comment by i8ramin** [comment] 2016-04-25 15:09
If you are using the old API (`$.cookie`), just fork the project and update your bower.json to point to `v1.5.1` of the project. versions `2.x.x` aren't backwards compatible with jquery.

`"js-cookie": "https://github.com/<YOUR REPO>/js-cookie.git#1.5.1"`

**Comment by R4YM3** [comment] 2016-04-25 15:10
+1

**Comment by FagnerMartinsBrack** [comment] 2016-04-25 15:10
Hey I have made no changes in the repository, this is definitely an external thing!

**Comment by gmrx38** [comment] 2016-04-25 15:11
+1 We get the same issue since this afternoon

**Comment by VEBERArnaud** [comment] 2016-04-25 15:12
just pinged Github Support on Twitter about this, do you guys know a better way to inform github about this issue ?

**Comment by ehmicky** [comment] 2016-04-25 15:16
I have the same problem.
It also seem to affect this repository: https://github.com/carhartl/jquery-cookie

**Comment by CaptainJojo** [comment] 2016-04-25 15:18
ok thank @FagnerMartinsBrack I send to github support

**Comment by gharcombe-minson** [comment] 2016-04-25 15:18
I also emailed github support about this issue a few minutes ago.

**Comment by FagnerMartinsBrack** [comment] 2016-04-25 15:18
I just sent to Github support in the [contact page](https://github.com/contact).

**Comment by FagnerMartinsBrack** [comment] 2016-04-25 15:19
I am having the same error when cloning via SSH:

```
git clone git@github.com:js-cookie/js-cookie.git js-cookie2
Cloning into 'js-cookie2'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by FagnerMartinsBrack** [comment] 2016-04-25 15:22
It seems to be general Github breakage, but not will all repos? https://twitter.com/i8ramin/status/724619167496822784
Bootstrap repo seems to be working, I am downloading it via HTTPS successfully.

**Comment by FagnerMartinsBrack** [comment] 2016-04-25 15:25
https://status.github.com/ says all systems operational. There is nothing I can do =(

**Comment by diegoavidal** [comment] 2016-04-25 15:35
temporary fix: 
fork the repo and:
bower install https://github.com/[repo]/js-cookie.git#v[version]

**Comment by FagnerMartinsBrack** [comment] 2016-04-25 15:40
Calling for help on Twitter: https://twitter.com/FagnerBrack/status/724620856232579074

The sooner Github support gets this the sooner it will be fixed.

**Comment by JoakimLofgren** [comment] 2016-04-25 15:41
I managed to add this in my bower.json file:
`"js-cookie": "https://github.com/js-cookie/js-cookie/releases/download/v1.5.1/js.cookie-1.5.1.min.js"`

Then I get a `index.js` file containing the things, not ideal, but I don't have to fork the repo.

**Comment by anolson** [comment] 2016-04-25 15:49
`/js-cookie/js-cookie.git` is redirecting to `/js-cookie/js-cookie`

```
$ curl -v https://github.com/js-cookie/js-cookie.git
*   Trying 192.30.252.122...
* Connected to github.com (192.30.252.122) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: github.com
* Server certificate: DigiCert SHA2 Extended Validation Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> GET /js-cookie/js-cookie.git HTTP/1.1
> Host: github.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: GitHub.com
< Date: Mon, 25 Apr 2016 15:45:25 GMT
< Content-Type: text/html
< Content-Length: 178
< Location: https://github.com/js-cookie/js-cookie
< Vary: Accept-Encoding
< X-Served-By: 29885c8097c6d503a86029451b2e021c
< X-GitHub-Request-Id: 60F0A02D:53FE:2DB54844:571E3B95
< X-Frame-Options: DENY
< 
```

**Comment by FagnerMartinsBrack** [comment] 2016-04-25 15:51
@anolson AFAIK it is supposed to be like that, see for example https://github.com/twbs/bootstrap.git

**Comment by bdaenen** [comment] 2016-04-25 15:52
@anolson Web requests to a github repository endpoint always seem to get redirected to the github page.

**Comment by anolson** [comment] 2016-04-25 15:53
@FagnerMartinsBrack @bdaenen You're both right, sorry for the confusion.

**Comment by FagnerMartinsBrack** [comment] 2016-04-25 16:02
Pinging some guys from bower/Github just in case they have any idea of what might be going on: @necolas, @paulirish, @addyosmani, @sindresorhus, @vladikoff, @mdo, @defunkt.

**Comment by tristanbes** [comment] 2016-04-25 16:06
Another case of leftpad effect ? :trollface:

**Comment by dodozhang21** [comment] 2016-04-25 16:07
Our workflow is being block as well.

**Comment by gharcombe-minson** [comment] 2016-04-25 16:08
I think it's fixed? Just cloned for me.

**Comment by FagnerMartinsBrack** [comment] 2016-04-25 16:08
> Another case of "leftpad" effect ? :trollface:

Dude, no idea. I haven't changed anything.

**Comment by FagnerMartinsBrack** [comment] 2016-04-25 16:08
I just cloned for me too!

**Comment by Keeo** [comment] 2016-04-25 16:09
This was nice opportunity to upgrade development tools.

**Comment by Chekote** [comment] 2016-04-25 16:10
@keeo Your avatar is quote appropriate.

**Comment by SeaOfTea** [comment] 2016-04-25 16:14
This seems to have cloned down now. It was stopping our build earlier.

**Comment by addyosmani** [comment] 2016-04-25 16:15
This appears to have been since addressed.

**Comment by FagnerMartinsBrack** [comment] 2016-04-25 16:22
If anybody knows what happened, please shout out!

I did a github research and it seems to have happened only for a couple of repositories. You can imagine how paranoid I was starting to be when sh1t started blowing out of the blue.

It's 2AM in Australia right now... oh boy. I am going to sleep, happy everything is fine now, @addyosmani sorry for bothering.

**Comment by carhartl** [comment] 2016-04-25 16:40
Almost certainly a glitch on GitHub. I was seeing the same when trying to clone another repo.

**Comment by FagnerMartinsBrack** [comment] 2016-04-25 22:52
Response from Github:

> Re: Mayday mayday. Sh1t is blowing.

> Hi Fagner,

> Sorry for the trouble. We were investigating reports earlier today of cloning and pushing problems in some repositories.

Confirmed as a temporary glitch. Closing since everything was fixed.

**Closed by FagnerMartinsBrack** 2016-04-25 22:52 UTC
