### ISSUE TITLE
URIError: malformed URI sequence

### ISSUE THREAD

**Issue by mrseanbaines** [js-cookie/js-cookie#637] opened 2020-06-15 13:08 UTC
**Describe the bug**
I am getting `URIError: malformed URI sequence` error thrown when using this package. It seems as though it's happening when ANY set cookie is invalid, even cookies that I'm not interacting with at all (e.g. a 3rd party cookie).

I'm using the latest version of this package (2.2.1)

**To Reproduce**
1. Go to any site using `js-cookie`
2. Go to console and manually set cookie like so `document.cookie = 'param=%A8'`
3. Refresh page

**Expected behavior**
No error to be thrown

**Screenshots**
<img width="482" alt="image" src="https://user-images.githubusercontent.com/24367010/84660023-30209280-af10-11ea-9ad5-2f380b923b33.png">

**Desktop (please complete the following information):**

- OS: macOS Catalina (10.15.5)
- Browser: Tested on Firefox and Chrome
- Version: FF v77.0.1 and Chrome v83.0.4103.97

**Comment by carhartl** [comment] 2020-06-15 13:45
@mrseanbaines 

Are you absolutely sure you're using version 2.2.1? It doesn't throw an error for me at all:

<img width="1274" alt="Screenshot 2020-06-15 at 15 42 07" src="https://user-images.githubusercontent.com/21918/84664618-1aff3000-af1f-11ea-954a-79fd7fb8e96b.png">

**Comment by carhartl** [comment] 2020-06-15 13:47
(And we have tests verifying that we don't throw an error in exactly such a case...)

**Comment by carhartl** [comment] 2020-06-15 13:49
Other things to note: the library doesn't read any cookies at all just by including it in the page, so there should be something in your application trying to read cookies?

Could be a React thing, but I don't see anything related to js-cookie in the trace.

Are you using custom converters maybe?

**Comment by carhartl** [comment] 2020-06-16 08:54
The error seems to originate from the `parseQueryString.js` module, I don't see any relation to js-cookie. Please provide a reproducible test case if you think the problem is still with js-cookie, closing for now.

**Closed by carhartl** 2020-06-16 08:54 UTC
Labels: bug

**Comment by mrseanbaines** [comment] 2020-06-16 09:50
Hmm, okay, thanks @carhartl. I checked the lockfile and I'm certain I'm using v2.2.1. I will try to reproduce the issue in a sandbox environment and open another ticket if needed.
