### ISSUE TITLE
getJSON called with many arguments doesn't behave as expected

### ISSUE THREAD

**Issue by cyrilchapon** [js-cookie/js-cookie#417] opened 2018-03-20 08:38 UTC
Following up on #416 

@carhartl
> getJSON(), in contrast to get(), we‘re passing on all given arguments. So what‘s actually happening when you called it with two arguments is each time a cookie is written (due to the api’s underlying implementation). You won’t notice the difference if the values remain the same, but that seems to be a bug. cc @FagnerMartinsBrack 

@carhartl 
> We have:

```
api.getJSON = function () {
    return api.apply({
        json: true
	}, arguments);
};
```
> and I believe we should have:

```
api.getJSON = function (key) {
    return api.call({ json: true }, key);
};
```

@carhartl 

> I believe it’s worse..

```
cookies.getJSON(k, {domain: 'a'})
```
> would result in a cookie k written with a value of json stringified {domain: 'a'}. Cannot test this right now.

**Comment by FagnerMartinsBrack** [comment] 2018-03-20 11:24
I'll use this one to respond the [previous thread](https://github.com/js-cookie/js-cookie/issues/416).

> [...] the API is not strongly documented about params

@cyrilchapon Totally agree. The only reason why we've never documented the parameters was that nobody has ever complained about this before.

> Nothing disallow me to think that get can take a second argument

I see. The example makes you think that `get` can take the second argument because it abstracts cookie internals and you can only know if you have the [Curse Of Knowledge](https://en.wikipedia.org/wiki/Curse_of_knowledge) of how `document.cookie` works. Myself and @carhartl are not in a position to know what should and what should not be documented, that's why feedback like this is great!

Perhaps we should document the limitations better for the retrieval.

In the README it says as a "note":

> IMPORTANT! When deleting a cookie, you must pass the exact same path and domain attributes that were used to set the cookie, unless you're relying on the default attributes.

It says nothing about retrieving a cookie, just removing it.

We can act on the same grounds of https://github.com/js-cookie/js-cookie/issues/145#issuecomment-205756498.

This is not a bug, [library internals do not exist](https://medium.com/@fagnerbrack/library-internals-do-not-exist-1ff50a30e3b0). However, it's an unexpected behavior that wouldn't happen if the API was better documented. We need to [avoid astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

The cause is also because of [the tradeoffs](https://github.com/js-cookie/js-cookie/issues/415#issuecomment-373881523) that lead to a poor internal design that leaked through to these undocumented behaviors.

**Comment by FagnerMartinsBrack** [comment] 2018-03-20 11:37
I'll put a summary of what has been talked so far:

1. @carhartl says we [should make the API side-effect free](https://github.com/js-cookie/js-cookie/issues/416#issuecomment-374517455).
2. @cyrilchapon said the arguments for the API [are not well documented](https://github.com/js-cookie/js-cookie/issues/416#issuecomment-374518921) and we should document it accordingly. Besides, the examples are too subjective.
3. @cyrilchapon suggested to ["Make methods accept .length by passing real arguments (it allows currying, for example)"](https://github.com/js-cookie/js-cookie/issues/416#issuecomment-374519501)
4. @cyrilchapon and @carhartl suggested to change the code for `return api.call({ json: true }, key);` instead of `api.apply({ json: true }, arguments);` to avoid `getJSON` to create a cookie when used with additional arguments.

I agree to **1**, **2** and **4**. I have no idea what **3** means.

My suggested actions are:

1. Document the cookie arguments accordingly following the existing README format and avoiding adding a lot of noise to the already big README.
2. iff there's no huge increase of GZip byte size for having the code `return api.call({ json: true }, key);`, just create a test and change it.

@carhartl @cyrilchapon What do you think?
@cyrilchapon can you elaborate on what **3** means?

**Comment by cyrilchapon** [comment] 2018-03-20 12:02
@FagnerMartinsBrack, basically [currying](https://en.wikipedia.org/wiki/Currying) tools ([lodash](https://lodash.com/docs/4.17.5#curry), [ramda](http://ramdajs.com/docs/#curry)) rely on `function.length`. Thus, I'm not sure...

```
function(/*empty*/) {
  // handle args with `arguments` context variable logic
}
```

...is compliant with that, which feels like a shame for a library nowadays. Just a side-note though, and I love this lib :)

**Comment by FagnerMartinsBrack** [comment] 2018-03-20 12:07
@cyrilchapon What's the benefit of using currying for the `Cookies.get(key)` API, given it only accepts one argument? It's not like you can partially apply the function, it's already fully applied when you call it with a single argument.

Besides, you could just wrap it yourself to add currying, since it may be a requirement from the paradigm being used in your application, not a fit for everybody else's use cases:

```javascript
const setCookie = (key) => (value) => (attributes) => {
  return Cookies.set(key, value, attributes);
};
```

Am I missing a use case here?

**Comment by carhartl** [comment] 2018-03-20 19:44
PR in the works..

**Comment by carhartl** [comment] 2018-04-13 06:11
Merged the fix, closing..

**Closed by carhartl** 2018-04-13 06:11 UTC
Labels: discussion
