### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by kkornwinkel** [js-cookie/js-cookie#387] opened 2017-12-12 17:33 UTC
Source-Map-Fehler: request failed with status 404
Ressourcen-Adresse: https://thekornydev.de/assets/js/cookies.js
Source-Map-Adresse: /sm/f6937b1819ab68f00d8b787ead6c16bfb67977e0c408909621a3b2ff82dbad4a.map

**Comment by FagnerMartinsBrack** [comment] 2018-01-11 04:09
Hi, thanks for opening an issue on js-cookie.

As stated in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/caa594ca966c967a8b72a317eddf446e5094caa8/CONTRIBUTING.md#issues), in order to take any further action we need a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) that shows a problem with js-cookie.

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

Closing for now, but once there's enough information that we can act upon just comment here so that we can reopen it.

If you create a StackOverflow question, please link it here so that we can help here or make it possible for others to find the answer. If you find a solution for your problem, please post it here too so that we can potentially improve the docs.

Don't let this stop you from keep contributing to js-cookie 👍 

Thank you!

**Closed by FagnerMartinsBrack** 2018-01-11 04:09 UTC

**Comment by courtneyaschwartz** [comment] 2019-08-06 21:27
Nothing in StackOverflow, and Google is ranking this issue in search results, so I'm putting this here.

This warning is currently reproducible in 2.2.0 and presumably 2.2.1 in Firefox 68.0.1 (64-bit; Win 10).

```
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://example.com/themes/lib/js.cookie.min.js?ver=2.2.0
Source Map URL: /sm/31d5cd1b58ce5e6231e4ea03a69b2801a53e76e98152bc29dc82a494ed0a1ee6.map
```
It happens if you use the line in README.MD here: 
https://github.com/js-cookie/js-cookie#direct-download

Background info/how to fix:
https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map
https://developer.mozilla.org/en-US/docs/Tools/Debugger/Source_map_errors#Invalid_source_map

**Comment by carhartl** [comment] 2019-08-06 22:17
We don‘t support source maps as part of our releases, so errors related to them should be related to the build system/dev environments in use by developers.

**Comment by FagnerMartinsBrack** [comment] 2019-08-07 02:51
@courtneyaschwartz As Klaus said, the error doesn't seem to be with js-cookie. You can post a new question on StackOverflow under the tag `js-cookie` and come up with a [SSCCE](http://sscce.org/) (Short, Self Contained, Correct (Compilable), Example) that proves a problem with js-cookie.
